[package]
name = "spl-2022-token"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.17"
spl-token-2022 = "0.9"
spl-associated-token-account = "2.0"

[dev-dependencies]
solana-program-test = "1.17"
solana-sdk = "1.17"

[lib]
crate-type = ["cdylib", "lib"] 